add custom colors and print to stderr option

diff --git a/common/log b/common/log
--- a/common/log
+++ b/common/log
@@ -1,31 +1,44 @@
 #! /bin/sh
 
+## option arguments
+option_color=0
+option_error=0
+
+## functions
 log_with_color() { echo -e "$(tput setaf $1)$2$(tput sgr0)"; }
 
-log_status() { echo -e "$(log_with_color "$1" "$2"):\t$3"; }
+log_with_status() { echo -e "$(log_with_color "$1" "$2"):\t$3"; }
 
-log_error() { log_status 1 "error" "$1" 1>&2; }
-log_info()  { log_status 2 "info"  "$1"; }
-log_warn()  { log_status 3 "warn"  "$1"; }
+log() {
+  if test $option_error -eq 0
+  then
+    log_with_status "$1" "$2" "$3"
+  else
+    log_with_status "$1" "$2" "$3" >&2
+  fi
+}
 
-
-## display usage
+### display usage
 usage() {
-  log_info "usage: log [-chqv] log_level message"
-  log_info ""
-  log_info "this script logs a message with a peceded log level"
-  log_info ""
-  log_info "arguments:"
-  log_info "  log_level"
-  log_info "    the log level to use (info, warn, error)"
-  log_info "  message"
-  log_info "    the message to log"
-  log_info ""
-  log_info "options:"
-  log_info "  -h, --help"
-  log_info "    display the usage information"
-  log_info "  -v, --version"
-  log_info "    display the version information"
+  log 2 "info" "usage: log [-cehv] [color] log_level message"
+  log 2 "info" ""
+  log 2 "info" "this script logs a message with a peceded log level"
+  log 2 "info" ""
+  log 2 "info" "arguments:"
+  log 2 "info" "  log_level"
+  log 2 "info" "    the log level to use (info, warn, error)"
+  log 2 "info" "  message"
+  log 2 "info" "    the message to log"
+  log 2 "info" ""
+  log 2 "info" "options:"
+  log 2 "info" "  -c, --color"
+  log 2 "info" "    specify the desired color"
+  log 2 "info" "  -e, --error"
+  log 2 "info" "    print using stderr instead of stdout"
+  log 2 "info" "  -h, --help"
+  log 2 "info" "    display the usage information"
+  log 2 "info" "  -v, --version"
+  log 2 "info" "    display the version information"
 
   exit 0
 }
@@ -38,6 +51,9 @@ do
     # normal option processing
     -h | --help)    usage ;;
     -v | --version) usage ;;
+
+    -c | --color) option_color=1 ;;
+    -e | --error) option_error=1 ;;
 
     # special cases
     --)  break ;;
@@ -59,11 +75,30 @@ do
   shift
 done
 
-### perform log based on first argument
+### setup log_color
+log_color=2 # green by default
+
+if test $option_color -eq 1
+then
+  log_color=$1
+  shift
+else
+  case $1 in
+    debug) log_color=2 ;;
+    error) log_color=1 ;;
+    fatal) log_color=1 ;;
+    info)  log_color=2 ;;
+    trace) log_color=2 ;;
+    warn)  log_color=3 ;;
+  esac
+fi
+
+### log message
 case $1 in
-  info)  log_info  $2 ;;
-  warn)  log_warn  $2 ;;
-  error) log_error $2 ;;
+  error | fatal)
+    log $log_color $1 "$2" >&2 ;;
+  *)
+    log $log_color $1 "$2" ;;
 esac
 
 exit 0
